trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Docker@2
  displayName: 'Build and push docker-image'
  inputs:
    containerRegistry: 'docker-hub'
    repository: 'dhedegaard/pollen-js'
    tags: 'latest'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: SSH@0
  displayName: 'Deploy new container'
  timeoutInMinutes: 10
  inputs:
    sshEndpoint: 'dennis@ymir'
    runOptions: 'inline'
    failOnStdErr: false
    inline: |
      bash -e -x -c "
        cd pollen-js &&
        git pull --ff-only &&
        docker pull dhedegaard/pollen-js &&
        docker stack deploy --prune -c docker-compose.yml pollen
      "